apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitek-wordpress
  namespace: habitek
  labels:
    app: habitek
spec:
  selector:
    matchLabels:
      app: habitek
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: habitek
        tier: frontend
    spec:
      containers:
        - image: wordpress:6.8.3-php8.1-apache
          name: habitek-wordpress
          envFrom:
            - secretRef:
                name: habitek-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: habitek-wordpress-persistent-storage
              mountPath: /var/www/html
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
              subPath: uploads.ini
          resources:
            requests:
              cpu: 4
              memory: 1024Mi
            limits:
              cpu: 6
              memory: 2048Mi
      volumes:
        - name: habitek-wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: habitek-wp-pv-claim
        - name: php-config
          configMap:
            defaultMode: 420
            name: wp-php-config
      securityContext:
        fsGroup: 33
        runAsUser: 33
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: habitek-wp-pv-claim
  namespace: habitek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 256M
    post_max_size = 256M
    memory_limit = 256M
    max_execution_time = 600
