apiVersion: v1
kind: Service
metadata:
  name: habitek-svc
  namespace: habitek
  labels:
    app: habitek-wordpress
spec:
  ports:
    - name: http
      targetPort: 80
      protocol: TCP
      port: 80
  type: ClusterIP
  selector:
    app: habitek-wordpress
    tier: frontend
