---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forom
  template:
    metadata:
      labels:
        app: forom
    spec:
      containers:
        - name: forom
          image: ghcr.io/clubcedille/forom:latest
          resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
            ports:
              - containerPort: 5173
