apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habitek-staging-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - habitek.prodv2.cedille.club
      secretName: habitek-tls
  rules:
    - host: habitek.prodv2.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: habitek-svc
                port:
                  number: 80
