apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: veloom-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: veloom.etsmtl.ca
      - op: replace
        path: /spec/tls/0/hosts/0
        value: veloom.etsmtl.ca
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/veloom-grav/default/grav
