---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forom-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - forom.prodv2.cedille.club
      secretName: forom-tls
  rules:
    - host: forom.prodv2.cedille.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forom-service
                port:
                  number: 5173
