apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: comets-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: comets.etsmtl.ca
      - op: replace
        path: /spec/tls/0/hosts/0
        value: comets.etsmtl.ca
  - target:
      kind: RandomSecret
      name: grav-init-pwd
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/comets-grav/default/grav
  - target:
      kind: RandomSecret
      name: grav-sre-pwd
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/comets-grav/default/grav
  - target:
      kind: RandomSecret
      name: grav-salt
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/comets-grav/default/grav