apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: comets-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: HTTPProxy
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: comets.etsmtl.ca
      - op: replace
        path: /spec/virtualhost/tls/secretName
        value: comets-grav-tls
      - op: replace
        path: /spec/routes/0/services/0/name
        value: comets-grav
  - target:
      kind: Certificate
      name: grav-tls
    patch: |-
      - op: replace
        path: /spec/secretName
        value: comets-grav-tls
      - op: replace
        path: /spec/commonName
        value: comets.etsmtl.ca
      - op: replace
        path: /spec/dnsNames/0
        value: comets.etsmtl.ca
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/comets-grav/default/grav
