apiVersion: v1
kind: Service
metadata:
  name: planifets-backend-service
spec:
  selector:
    app: planifets-backend
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
