apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: preview-ingress
spec:
  virtualhost:
    fqdn: preview.prodv2.cedille.club
    tls:
      secretName: preview-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      services:
        - name: placeholder-service
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-tls
spec:
  secretName: preview-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: preview.prodv2.cedille.club
  dnsNames:
    - preview.prodv2.cedille.club
