apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comets-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - comets.prodv2.cedille.club
      secretName: cedille-cert-tls
  rules:
    - host: comets.prodv2.cedille.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comets-web-service
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comets-web-ingress-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - comets.etsmtl.ca
      secretName: cedille-cert-tls-prod
  rules:
    - host: comets.etsmtl.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comets-web-service
                port:
                  name: http
