apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veloom-prod-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - veloom.etsmtl.ca
      secretName: veloom-prod-tls
  rules:
    - host: veloom.ca
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: veloom-svc
                port:
                  number: 80
