apiVersion: projectcontour.io/v1
kind: HTTPProxy
spec:
  virtualhost:
    fqdn: evovelo.etsmtl.ca
    tls:
      secretName: veloom-prod-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: veloom-svc
          port: 80
      requestPolicy:
        allow:
          headers:
            - Content-Type
            - Authorization
      cors:
        allowOrigin:
          - "https://evovelo.etsmtl.ca"
          - "https://evovelo.cedille.club"
        allowMethods:
          - "*"
        allowHeaders:
          - "*"
