apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veloom-staging-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - veloom-wp.prodv2.cedille.club
      secretName: veloom-staging-tls
  rules:
    - host: veloom.prodv2.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: veloom-svc
                port:
                  number: 80
