apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - acets-grav.yaml
  - aeroets-grav.yaml
  - comets-grav.yaml
  - crabeweb-grav.yaml
  - raconteurs-grav.yaml
