apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: acets-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: HTTPProxy
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: acets.prodv2.cedille.club
      - op: replace
        path: /spec/virtualhost/tls/secretName
        value: acets-grav-tls
      - op: replace
        path: /spec/routes/0/services/0/name
        value: acets-grav
  - target:
      kind: Certificate
      name: grav-tls
    patch: |-
      - op: replace
        path: /spec/secretName
        value: acets-grav-tls
      - op: replace
        path: /spec/commonName
        value: acets.prodv2.cedille.club
      - op: replace
        path: /spec/dnsNames/0
        value: acets.prodv2.cedille.club
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-prod
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/acets-grav/default/grav
