annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump Penpot to 2.11.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: support
      url: https://github.com/penpot/penpot-helm/issues
    - name: community
      url: https://community.penpot.app
    - name: documentation
      url: https://help.penpot.app
    - name: tutorials
      url: https://www.youtube.com/playlist?list=PLgcCPfOv5v54WpXhHmNO7T-YC7AE-SRsr
    - name: dev-diaries
      url: https://penpot.app/dev-diaries.html
  artifacthub.io/signKey: |
    fingerprint: F0B526DC641A6DCBD94A2B2BA11A82757E9E6942
    url: https://helm.penpot.app/pubkey.asc
apiVersion: v2
appVersion: 2.11.0
dependencies:
- condition: global.postgresqlEnabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.5.38
- condition: global.valkeyEnabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.31
- condition: global.redisEnabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.6.4
description: Helm chart for Penpot, the Open Source design and prototyping platform.
home: https://penpot.app
icon: https://avatars.githubusercontent.com/u/30179644?s=200&v=4
keywords:
- kubernetes
- penpot
- penpotapp
- design
- designsystem
- opensource
- ux
- ui
maintainers:
- name: Kaleidos INC
  url: https://kaleidos.net
name: penpot
sources:
- https://github.com/penpot/penpot/tree/main
- https://github.com/penpot/penpot-helm/tree/main
type: application
version: 0.29.0
