apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planifets-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - secretName: planifets-service-tls
      hosts:
        - planifets.prodv2.cedille.club
  rules:
    - host: backend.planifets.prodv2.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: planifets-backend-service
                port:
                  number: 3000
    - host: planifets.prodv2.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: planifets-frontend-service
                port:
                  number: 3000
