apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-prod-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - vault.prodv2.cedille.club
      secretName: vault-prod-tls
  rules:
    - host: vault.prodv2.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200
