apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: crabeweb-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: crabe.demo.prodv2.cedille.club
      - op: replace
        path: /spec/tls/0/hosts/0
        value: crabe.demo.prodv2.cedille.club
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/crabeweb-grav/default/grav
  - target:
      kind: Deployment
      name: grav
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/clubcedille/grav:demo-crabe
  - target:
      kind: Deployment
      name: grav
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /accueil
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io/cluster-issuer
        value: letsencrypt-prod
