apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: crabeweb-

resources:
  - ../../../../bases/grav
  - httpproxy.yaml

patches:
  - path: vault-patch.yaml
  - target:
      kind: HTTPProxy
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: crabe.etsmtl.ca
      - op: replace
        path: /spec/virtualhost/tls/secretName
        value: grav-tls-prod
      - op: replace
        path: /spec/routes/0/services/0/name
        value: crabeweb-grav
  - target:
      kind: Certificate
      name: grav-tls
    patch: |-
      - op: replace
        path: /spec/secretName
        value: grav-tls-prod
      - op: replace
        path: /spec/commonName
        value: crabe.etsmtl.ca
      - op: replace
        path: /spec/dnsNames/0
        value: crabe.etsmtl.ca
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-prod
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/crabeweb-grav/default/grav
  - target:
      kind: Deployment
      name: grav
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /accueil
